#!/usr/bin/env bash
# Copyright 2023 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

if [[ "$RUNTIME" == "wasmtime" ]]; then
    env_vars=$(env -0 | xargs -0 -I {} echo "--env {}")
	exec wasmtime run --dir=/ "${env_vars}" $1 -- "${@:2}"
else
    exec wazero run -mount /:/ -env-inherit -cachedir "${TMPDIR}"/wazero $1 "${@:2}"
fi
